
*****************************************************************************

[('DatabaseShopper', <class 'gourmet.recipeManager.DatabaseShopper'>),
 ('RecData', <class 'gourmet.backends.db.RecData'>),
 ('RecipeManager', <class 'gourmet.backends.db.RecipeManager'>),
 ('SimpleCLI', <class 'gourmet.recipeManager.SimpleCLI'>),
 ('__builtins__',
   {'ArithmeticError': <class 'ArithmeticError'>,
   'AssertionError': <class 'AssertionError'>,
   'AttributeError': <class 'AttributeError'>,
   'BaseException': <class 'BaseException'>,
   'BaseExceptionGroup': <class 'BaseExceptionGroup'>,
   'BlockingIOError': <class 'BlockingIOError'>,
   'BrokenPipeError': <class 'BrokenPipeError'>,
   'BufferError': <class 'BufferError'>,
   'BytesWarning': <class 'BytesWarning'>,
   'ChildProcessError': <class 'ChildProcessError'>,
   'ConnectionAbortedError': <class 'ConnectionAbortedError'>,
   'ConnectionError': <class 'ConnectionError'>,
   'ConnectionRefusedError': <class 'ConnectionRefusedError'>,
   'ConnectionResetError': <class 'ConnectionResetError'>,
   'DeprecationWarning': <class 'DeprecationWarning'>,
   'EOFError': <class 'EOFError'>,
   'Ellipsis': Ellipsis,
   'EncodingWarning': <class 'EncodingWarning'>,
   'EnvironmentError': <class 'OSError'>,
   'Exception': <class 'Exception'>,
   'ExceptionGroup': <class 'ExceptionGroup'>,
   'False': False,
   'FileExistsError': <class 'FileExistsError'>,
   'FileNotFoundError': <class 'FileNotFoundError'>,
   'FloatingPointError': <class 'FloatingPointError'>,
   'FutureWarning': <class 'FutureWarning'>,
   'GeneratorExit': <class 'GeneratorExit'>,
   'IOError': <class 'OSError'>,
   'ImportError': <class 'ImportError'>,
   'ImportWarning': <class 'ImportWarning'>,
   'IndentationError': <class 'IndentationError'>,
   'IndexError': <class 'IndexError'>,
   'InterruptedError': <class 'InterruptedError'>,
   'IsADirectoryError': <class 'IsADirectoryError'>,
   'KeyError': <class 'KeyError'>,
   'KeyboardInterrupt': <class 'KeyboardInterrupt'>,
   'LookupError': <class 'LookupError'>,
   'MemoryError': <class 'MemoryError'>,
   'ModuleNotFoundError': <class 'ModuleNotFoundError'>,
   'NameError': <class 'NameError'>,
   'None': None,
   'NotADirectoryError': <class 'NotADirectoryError'>,
   'NotImplemented': NotImplemented,
   'NotImplementedError': <class 'NotImplementedError'>,
   'OSError': <class 'OSError'>,
   'OverflowError': <class 'OverflowError'>,
   'PendingDeprecationWarning': <class 'PendingDeprecationWarning'>,
   'PermissionError': <class 'PermissionError'>,
   'ProcessLookupError': <class 'ProcessLookupError'>,
   'RecursionError': <class 'RecursionError'>,
   'ReferenceError': <class 'ReferenceError'>,
   'ResourceWarning': <class 'ResourceWarning'>,
   'RuntimeError': <class 'RuntimeError'>,
   'RuntimeWarning': <class 'RuntimeWarning'>,
   'StopAsyncIteration': <class 'StopAsyncIteration'>,
   'StopIteration': <class 'StopIteration'>,
   'SyntaxError': <class 'SyntaxError'>,
   'SyntaxWarning': <class 'SyntaxWarning'>,
   'SystemError': <class 'SystemError'>,
   'SystemExit': <class 'SystemExit'>,
   'TabError': <class 'TabError'>,
   'TimeoutError': <class 'TimeoutError'>,
   'True': True,
   'TypeError': <class 'TypeError'>,
   'UnboundLocalError': <class 'UnboundLocalError'>,
   'UnicodeDecodeError': <class 'UnicodeDecodeError'>,
   'UnicodeEncodeError': <class 'UnicodeEncodeError'>,
   'UnicodeError': <class 'UnicodeError'>,
   'UnicodeTranslateError': <class 'UnicodeTranslateError'>,
   'UnicodeWarning': <class 'UnicodeWarning'>,
   'UserWarning': <class 'UserWarning'>,
   'ValueError': <class 'ValueError'>,
   'Warning': <class 'Warning'>,
   'ZeroDivisionError': <class 'ZeroDivisionError'>,
   '__build_class__': <built-in function __build_class__>,
   '__debug__': False,
   '__doc__': 'Built-in functions, types, exceptions, and other objects.\n'
              '\n'
              "This module provides direct access to all 'built-in'\n"
              'identifiers of Python; for example, builtins.len is\n'
              'the full name for the built-in function len().\n'
              '\n'
              'This module is not normally accessed explicitly by most\n'
              'applications, but can be useful in modules that provide\n'
              'objects with the same name as a built-in value, but in\n'
              'which the built-in of that name is also needed.',
   '__import__': <built-in function __import__>,
   '__loader__': <class '_frozen_importlib.BuiltinImporter'>,
   '__name__': 'builtins',
   '__package__': '',
   '__spec__': ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>, origin='built-in'),
   'abs': <built-in function abs>,
   'aiter': <built-in function aiter>,
   'all': <built-in function all>,
   'anext': <built-in function anext>,
   'any': <built-in function any>,
   'ascii': <built-in function ascii>,
   'bin': <built-in function bin>,
   'bool': <class 'bool'>,
   'breakpoint': <built-in function breakpoint>,
   'bytearray': <class 'bytearray'>,
   'bytes': <class 'bytes'>,
   'callable': <built-in function callable>,
   'chr': <built-in function chr>,
   'classmethod': <class 'classmethod'>,
   'compile': <built-in function compile>,
   'complex': <class 'complex'>,
   'copyright': Copyright (c) 2001-2023 Python Software Foundation.
All Rights Reserved.

Copyright (c) 2000 BeOpen.com.
All Rights Reserved.

Copyright (c) 1995-2001 Corporation for National Research Initiatives.
All Rights Reserved.

Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.
All Rights Reserved.,
   'credits':     Thanks to CWI, CNRI, BeOpen.com, Zope Corporation and a cast of thousands
    for supporting Python development.  See www.python.org for more information.,
   'delattr': <built-in function delattr>,
   'dict': <class 'dict'>,
   'dir': <built-in function dir>,
   'divmod': <built-in function divmod>,
   'enumerate': <class 'enumerate'>,
   'eval': <built-in function eval>,
   'exec': <built-in function exec>,
   'exit': Use exit() or Ctrl-D (i.e. EOF) to exit,
   'filter': <class 'filter'>,
   'float': <class 'float'>,
   'format': <built-in function format>,
   'frozenset': <class 'frozenset'>,
   'getattr': <built-in function getattr>,
   'globals': <built-in function globals>,
   'hasattr': <built-in function hasattr>,
   'hash': <built-in function hash>,
   'help': Type help() for interactive help, or help(object) for help about object.,
   'hex': <built-in function hex>,
   'id': <built-in function id>,
   'input': <built-in function input>,
   'int': <class 'int'>,
   'isinstance': <built-in function isinstance>,
   'issubclass': <built-in function issubclass>,
   'iter': <built-in function iter>,
   'len': <built-in function len>,
   'license': Type license() to see the full license text,
   'list': <class 'list'>,
   'locals': <built-in function locals>,
   'map': <class 'map'>,
   'max': <built-in function max>,
   'memoryview': <class 'memoryview'>,
   'min': <built-in function min>,
   'next': <built-in function next>,
   'object': <class 'object'>,
   'oct': <built-in function oct>,
   'open': <built-in function open>,
   'ord': <built-in function ord>,
   'pow': <built-in function pow>,
   'print': <built-in function print>,
   'property': <class 'property'>,
   'quit': Use quit() or Ctrl-D (i.e. EOF) to exit,
   'range': <class 'range'>,
   'repr': <built-in function repr>,
   'reversed': <class 'reversed'>,
   'round': <built-in function round>,
   'set': <class 'set'>,
   'setattr': <built-in function setattr>,
   'slice': <class 'slice'>,
   'sorted': <built-in function sorted>,
   'staticmethod': <class 'staticmethod'>,
   'str': <class 'str'>,
   'sum': <built-in function sum>,
   'super': <class 'super'>,
   'tuple': <class 'tuple'>,
   'type': <class 'type'>,
   'vars': <built-in function vars>,
   'zip': <class 'zip'>}),
 ('__cached__',
  '/zopt/src/gourmet/src/gourmet/__pycache__/recipeManager.cpython-311.pyc'),
 ('__doc__', None),
 ('__file__', '/zopt/src/gourmet/src/gourmet/recipeManager.py'),
 ('__loader__',
  <_frozen_importlib_external.SourceFileLoader object at 0x7f36b6f85f10>),
 ('__name__', 'gourmet.recipeManager'),
 ('__package__', 'gourmet'),
 ('__spec__',
  ModuleSpec(name='gourmet.recipeManager', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f36b6f85f10>, origin='/zopt/src/gourmet/src/gourmet/recipeManager.py')),
 ('args',
  Namespace(db_url='sqlite:////home/liam/stuff/recipes/Asian.db', threads=False, gourmetdir='', thread_debug_interval=5.0, thread_debug=False, debug_file='', time=False, debug=False)),
 ('convert',
  <module 'gourmet.convert' from '/zopt/src/gourmet/src/gourmet/convert.py'>),
 ('dbDic', <class 'gourmet.backends.db.dbDic'>),
 ('dbargs',
  {'custom_url': 'sqlite:////home/liam/stuff/recipes/Asian.db',
   'file': '/home/liam/.gourmet/recipes.db'}),
 ('de',
  <module 'gourmet.gtk_extras.dialog_extras' from '/zopt/src/gourmet/src/gourmet/gtk_extras/dialog_extras.py'>),
 ('default_rec_manager', <function default_rec_manager at 0x7f36b6b25120>),
 ('get_recipe_manager', <function get_recipe_manager at 0x7f36b6e758a0>),
 ('gglobals',
  <module 'gourmet.gglobals' from '/zopt/src/gourmet/src/gourmet/gglobals.py'>),
 ('os', <module 'os' (frozen)>),
 ('shopping',
  <module 'gourmet.shopping' from '/zopt/src/gourmet/src/gourmet/shopping.py'>)]

*****************************************************************************
