[book]
authors = ["GaelicGrime"]
language = "en"
multilingual = false
src = "src"
title = "TITLE"

[output.html]
theme = "theme"
default-theme = "dark"
preferred-dark-theme = "navy"
curly-quotes = true
copy-fonts = true
no-section-label = false
